/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ExploreRouteImport } from './routes/explore'
import { Route as LoginRouteImport } from './routes/login'
import { Route as SsoRouteImport } from './routes/sso'
import { Route as ApiCubejsV1LoadRouteImport } from './routes/api/cubejs/v1/load'
import { Route as ApiCubejsV1MetaRouteImport } from './routes/api/cubejs/v1/meta'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreRoute = ExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const SsoRoute = SsoRouteImport.update({
  id: '/sso',
  path: '/sso',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCubejsV1LoadRoute = ApiCubejsV1LoadRouteImport.update({
  id: '/api/cubejs/v1/load',
  path: '/api/cubejs/v1/load',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCubejsV1MetaRoute = ApiCubejsV1MetaRouteImport.update({
  id: '/api/cubejs/v1/meta',
  path: '/api/cubejs/v1/meta',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/explore': typeof ExploreRoute
  '/login': typeof LoginRoute
  '/sso': typeof SsoRoute
  '/api/cubejs/v1/load': typeof ApiCubejsV1LoadRoute
  '/api/cubejs/v1/meta': typeof ApiCubejsV1MetaRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/explore': typeof ExploreRoute
  '/login': typeof LoginRoute
  '/sso': typeof SsoRoute
  '/api/cubejs/v1/load': typeof ApiCubejsV1LoadRoute
  '/api/cubejs/v1/meta': typeof ApiCubejsV1MetaRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/explore': typeof ExploreRoute
  '/login': typeof LoginRoute
  '/sso': typeof SsoRoute
  '/api/cubejs/v1/load': typeof ApiCubejsV1LoadRoute
  '/api/cubejs/v1/meta': typeof ApiCubejsV1MetaRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/explore'
    | '/login'
    | '/sso'
    | '/api/cubejs/v1/load'
    | '/api/cubejs/v1/meta'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/explore'
    | '/login'
    | '/sso'
    | '/api/cubejs/v1/load'
    | '/api/cubejs/v1/meta'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/explore'
    | '/login'
    | '/sso'
    | '/api/cubejs/v1/load'
    | '/api/cubejs/v1/meta'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  ExploreRoute: typeof ExploreRoute
  LoginRoute: typeof LoginRoute
  SsoRoute: typeof SsoRoute
  ApiCubejsV1LoadRoute: typeof ApiCubejsV1LoadRoute
  ApiCubejsV1MetaRoute: typeof ApiCubejsV1MetaRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore': {
      id: '/explore'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof ExploreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sso': {
      id: '/sso'
      path: '/sso'
      fullPath: '/sso'
      preLoaderRoute: typeof SsoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cubejs/v1/load': {
      id: '/api/cubejs/v1/load'
      path: '/api/cubejs/v1/load'
      fullPath: '/api/cubejs/v1/load'
      preLoaderRoute: typeof ApiCubejsV1LoadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cubejs/v1/meta': {
      id: '/api/cubejs/v1/meta'
      path: '/api/cubejs/v1/meta'
      fullPath: '/api/cubejs/v1/meta'
      preLoaderRoute: typeof ApiCubejsV1MetaRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  ExploreRoute: ExploreRoute,
  LoginRoute: LoginRoute,
  SsoRoute: SsoRoute,
  ApiCubejsV1LoadRoute: ApiCubejsV1LoadRoute,
  ApiCubejsV1MetaRoute: ApiCubejsV1MetaRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
